import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactCompiler: true,

  images: {
    // Next 16 restricts quality to this allowlist and silently coerces anything
    // else to the nearest entry. The logo is a lossy JPEG, so re-encoding it at
    // the default 75 compounds the compression and blurs the mark — 95 is
    // allowed here so the header can opt into a near-lossless re-encode.
    qualities: [75, 95],
  },

  async headers() {
    return [
      {
        // The climate JSON and boundary GeoJSON are regenerated by the backend
        // scripts, not per deploy, and are large enough that a repeat visit
        // re-downloading them is the slowest thing the app does. Cache them for
        // a day and allow a stale copy to be served while revalidating.
        source: "/:dir(data|geojson)/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=86400, stale-while-revalidate=604800",
          },
        ],
      },
    ];
  },

  async redirects() {
    return [
      {
        // The FAQ now lives as a section of /about.
        source: "/faq",
        destination: "/about#faq",
        permanent: true,
      },
    ];
  },
};

export default nextConfig;
